This is how the "submit" method of the "ExecutorService" interface is defined - 

    Future<?> submit(Runnable task);

So, unlike the "Executor" interface's "execute" method which returns nothing, the "submit" method of the "ExecutorService" interface does return something.

This something is "Future". What is this "Future"?

Well, if you go into the definiton, "Future" is an interface and it is part of the "java.util.concurrent" package.

A "Future" represents the result of an asynchronous operation.

A Future provides a mechanism to retrieve the result of a computation that may not be completed yet, allowing non-blocking operations in multi-threaded environments.

Let's see the following piece of code - 

    ExecutorService executorService = Executors.newSingleThreadExecutor();
    Future<Integer> future = executorService.submit(() -> 42);
    System.out.println(future.get());
    executorService.shutdown();

So here, we used the "submit" method of the ExecutorService and then passed a "Runnable" in it in the form of a lambda expression. This runnable just returns "42".

Now, this "return" value is what we can get using the "Future". Assume that this "42" was returned after three seconds. This means that before those 3 seconds, we wouldn't get anything returned back to us. "Future" is a type that we can use in this case. Whenever something is returned by this "submit" method, then that will be stored in the "Future" type. 

And then, we can use the "get()" method of this "Future" to retrieve whatever was returned.

You might think what if we have some other code after the "get" method which needs what is returned and put in Future variable. Well, in that case, that code has to wait. 

That's because the get() method blocks the calling thread until the result is available or the task is done.

To see this in action, let's add some delay.

        Future<Integer> future = executorService.submit(() -> {
            Thread.sleep(3000);
            return 42;
        });

        System.out.println(future.get());

        System.out.println("This line will be called after we get the result of the computation!");

        executorService.shutdown();

If you run the above code, you will see that the terminal will not print anything for 3 seconds. And then ,it prints "42" and also the next print statement.

This shows that "get" will block the main thread until the result is available.

So, does this mean we always need to return something in our "Runnable" that we pass to "submit" method? Well, no.

We can have something like this too -

    Future<Integer> future = executorService.submit(() -> System.out.println("Hello World"));

    System.out.println(future.get());

In this case, since nothing is returned, the "future.get()" will give us "null".

But, the benefit of this "Future" interface is that it has various method that we can use to our advantage. For example, we might want to run some code when this computation finishes.

In that case, we have a method named "isDone()".

    Future<?> future = executorService.submit(() -> System.out.println("Hello World"));
    
    System.out.println(future.get());
    
    if(future.isDone()) {
        System.out.println("Task Completed!");
    }
        
Note that if you call "isDone" before you call "get()" then this won't run. That's because only when we call "get()", then it will block the main thread and let the computation finish first. And only after that future will be done.

Otherwise, if we have - 

    Future<?> future = executorService.submit(() -> System.out.println("Hello World"));
        
    if(future.isDone()) {
        System.out.println("Task Completed!");
    }

In this case, the main thread will run the "future.isDone" code instantly when we run the application and so, "isDone" will be false that time.

# future.get() WITH TIMEOUT

Let's take an example where a task takes some time and we want to get the result within some time and if in that time frame we do not get the result, an exception is thrown.

If we have -

    Future<Integer> future = executorService.submit(() -> {
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        return 42;
    });

We can call "future.get" but this time, we can pass a timeout value which is the timeout value till which we wait and if in that time we do not get the result, the "TimeoutException" is thrown.

    try {
        Integer i = future.get(1, TimeUnit.SECONDS);
        System.out.println(future.isDone());
        System.out.println("Result is -> "+ i);
    } catch (InterruptedException | ExecutionException | TimeoutException e) {
        System.out.println("Exception Occurred: " + e);
    }

Since our task waits for 2 seconds but the timeout of Future is 1 second, the above code will throw a "TimeoutException".

# cancel() and isCancelled()

If there is some task that has been submitted to the "ExecutorService" or is otherwise being run asynchronously and want to cancel its execution, then we can cancel that task using "future.cancel()" method.

This is the method signature - 

    boolean cancel(boolean mayInterruptIfRunning);

So, it takes an argument "mayInterruptIfRunning" which is a boolean. If we pass "true", then the task is interrupted if it is already running. If we pass "false", the task is allowed to complete if it is already running.

    Future<Integer> future = executorService.submit(() -> {
            try {
                Thread.sleep(2000);
                System.out.println("Inside task!");
            } catch (InterruptedException e) {
                System.out.println("Thread Interrupted!");
                throw new RuntimeException(e);
            }
            return 42;
        });

In above code, we have a task that takes at least "2" seconds to execute. So, if we write - 

    future.cancel(true);

This will immediately stop the execution because since the flag is true, even if the task was being executed in a different thread, it will be interrupted.

Now, to really see this behavior in action, let's add some delay in the main thread so that the above task actually starts executing in that time. And then, we call "cancel" with "false".

    try {
        Thread.sleep(1000);
    } catch (InterruptedException e) {
        throw new RuntimeException(e);
    }
    
    future.cancel(false);

You will see that the terminal will print - 

    Inside task!

This means, even if we called "cancel" it did not stopped the execution of the task in that other thread. That's because the task was already started and also, we passed the flag as "false" which means if the task is started, it will wait for that task to complete.

But, let's see what happens when we call the "cancel" method with "true".

    try {
        Thread.sleep(1000);
    } catch (InterruptedException e) {
        throw new RuntimeException(e);
    }
    future.cancel(true);

In this case, the terminal will print - 

    Thread Interrupted!

That's because even if the Thread was executing the task, since we called "cancel" with "true" it will attempt to stop the execution by interrupting the thread, which it did in our case.

There is another method named "isCancelled" which, as the name says, returns True or False depending on whether the "Future/Task" was canelled or not.

So, if we write - 

    try {
        Thread.sleep(1000);
    } catch (InterruptedException e) {
        throw new RuntimeException(e);
    }
    
    future.cancel(true);
    System.out.println(future.isCancelled());

This will print -

    Thread Interrupted!
    true

It will return "false" if the task could not be canceled, either because it has already completed or been canceled. Now, one thing to note is that if in the above code, we had - 

    try {
        Thread.sleep(1000);
    } catch (InterruptedException e) {
        throw new RuntimeException(e);
    }
    
    future.cancel(false);
    System.out.println(future.isCancelled());

You may think that since we pass "false", it means since the task associated with the future is already running, it will not be cancelled so the "future.isCancelled()" should return "false". But that is not the case. When we call "future.cancel", then it will mark that "future" as cancelled, doesn't matter if the task associated with it is stopped or not.

So the conclusion is - 

    If the task hasn't started yet, it will be canceled without ever running.

    If the task is running and "mayInterruptIfRunning" is set to true, the thread running the task will be interrupted.
    
    If the task is already completed or cannot be canceled, it will return false.

# isDone()

If the task that is represented by a future is "complete" then this method returns "true", otherwise "false".

Completion may be due to normal termination, an exception, or cancellation -- in all of these cases, this method will return "true".

If the task is still running or not yet started, then it returns "false".

If "isDone()" returns true, you can safely call "Future.get()" to retrieve the result or handle any exceptions.

To see this in action, let's define a task that takes some time - 

    Future<Integer> future = executor.submit(() -> {
        Thread.sleep(3000);
        return 42; // Some result
    });

Now, we can use "isDone" to check if the task is complete. If not, we can wait for it to complete.

    while(!future.isDone()) {
        System.out.println("Task is still running...");
        try {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }

And once it is complete, we can now get the result - 

    try {
        System.out.println("Task Completed. Result: "+ future.get());
    } catch (InterruptedException | ExecutionException e) {
        throw new RuntimeException(e);
    }

    executorService.shutdown();

So, we will see in terminal something like this - 

    Task is still running...
    Task is still running...
    Task is still running...
    Task is still running...
    Task is still running...
    Task is still running...
    Task Completed. Result: 42